volumes:
  fastapidemo-data:
    external: true

services:
  postgres:
    image: postgres:15.2-bullseye
    environment:
      POSTGRES_PASSWORD: 9A4Sad6nF0yIJP3QSUq5
      POSTGRES_USER: wlotus
      POSTGRES_DB: fastapidemo_db
    ports:
      - 15432:5432
    volumes:
      - fastapidemo-data:/var/lib/postgresql/data

  fastapi:
    environment:
      DATABASE_URL: postgresql://wlotus:9A4Sad6nF0yIJP3QSUq5@postgres/fastapidemo_db
      WAIT_HOSTS: postgres:5432
      PORT: 8000
      WAIT_BEFORE: 5
      WAIT_TIMEOUT: 60

    build:
      context: ./app
      dockerfile: Dockerfile.dev
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
